---

version: "3.3"

services:

  nginx:
    build:
      context: docker-config/nginx
      dockerfile: Dockerfile
    image: "gmir/docker-nginx:latest"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker-config/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: docker-config/php
      dockerfile: Dockerfile
    image: "gmir/docker-php-fpm:latest"
    container_name: php
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_NAME}
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker-config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  node:
    build:
      context: docker-config/node
      dockerfile: Dockerfile
    image: "gmir/docker-node:latest"
    container_name: node
    working_dir: ${DOCUMENT_ROOT}
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./logs/npm:/root/.npm/_logs
    networks:
          - appnet
    command: "npm run watch-poll"

  database:
    image: "mysql:latest"
    container_name: database
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - appnet
    ports:
      - '8080:80'

networks:
  appnet:
    driver: "bridge"

volumes:
    nginx_db_data:
